### ISSUE TITLE
When 'noImplicitAny' enabled ts doesn't compile

### ISSUE THREAD

**Issue by ubenzer** [tomastrajan/ngx-model#2]
Hello,

I have an application in which I use ngx-model. My application has the following in `tsconfig.json`:

```json
"strict": true,
"skipLibCheck": true
```

`strict` enables `noImplicitAny`. When I try to use `ngx-model` in this setup, I get the following error:

`ERROR in /node_modules/ngx-model/lib/model.ts (39,41): Parameter 'clone' implicitly has an 'any' type.`

While trying to find solution I saw [this](https://github.com/Microsoft/TypeScript/issues/15363#issuecomment-296854812), which explains why I get this error. 

Is it possible to publish `d.ts` files?

**Comment by tomastrajan** [comment]
Definitelly something worth looking into. Will check whag are the tradeoffs of distributing ts vs .d.ts and js.

**Comment by tomastrajan** [comment]
For now I would go with just adding the type to that `createWithCustomClone(initialData: T, clone: (data: T) => T) {` function because it is already typed in nested call. This will solve your issue. Also added `tsconfig.json` to run tests against that config. This bugfix can theoretically break someones code in case they are passing clone function with different signature so will do a major release.

**Comment by tomastrajan** [comment]
Please let me know if this helped 😉

**Comment by ubenzer** [comment]
This solved the problem I faced. Thanks for addressing this so quickly!
