### ISSUE TITLE
Take a look at immer

### ISSUE THREAD

**Issue by leiserfg** [tomastrajan/ngx-model#4]
https://github.com/mweststrate/immer
It can be a fast alternative to JSONing a deJSONing the Model. (Needs testing)

**Comment by tomastrajan** [comment]
I heard about itband sounded very interesting. Dont know how it works with generic "clone everything" but is definitelly worth looking into. PR maybe ? 😉

**Comment by tomastrajan** [comment]
Ok, was checking it and as it seems immer is more useful for situations where cloning is implemented by the developer himself like for example when implementing reducers.  The ngx-model on the other hand tries to hide cloning from the developer. The cloning is handled by the library in a "handles most situation out of the box" way.  

I can't really use immer for implementing library wide cloning because I don't know the details about the data which particular developer will be passing to the model. 

Hope that I understood immer correctly and this reasons make sense.

Thank you again for the suggestion.
